# Generated by Django 2.2.14 on 2020-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200909_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yr',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
